services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatMiniProgramShareBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  WechatMiniProgramShareBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatMiniProgramShareBundle\Procedure\:
    resource: '../../Procedure/'
  WechatMiniProgramShareBundle\Repository\:
    resource: '../../Repository/'
  WechatMiniProgramShareBundle\Service\:
    resource: '../../Service/'

  wechat-mini-program-share.hashids:
    class: Hashids\Hashids
    factory: ['WechatMiniProgramShareBundle\Service\HashidsFactory', 'createHashids']
