services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatMiniProgramShareBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatMiniProgramShareBundle\Procedure\:
    resource: '../../Procedure/'
  WechatMiniProgramShareBundle\Repository\:
    resource: '../../Repository/'

  wechat-mini-program-share.hashids:
    class: Hashids\Hashids
    public: true
    arguments:
      - '%env(HASHID_SALT)%'
      - 10
